;#<?php exit(); ?>##
config_version = 34

;#########################################################
; Database                                               #
;#########################################################

database_hostname = "%%DB_HOST%%"
database_port = "%%DB_PORT%%"
database_name = "%%DB_NAME%%"
database_username = "%%DB_USER%%"
database_password = "%%DB_PASS%%"


;#########################################################
; Session and Security                                   #
;#########################################################

; Cryptographic secret
secret_key = "abcdefghijklmnoprqstuvwyz0123456"


;#########################################################
; Program Settings                                       #
;#########################################################

wanted = "true"
podcast = "true"
;websocket_address = "ws://localhost:8100"
show_footer_statistics = "false"


;#########################################################
; Public Registration settings, defaults to disabled     #
;#########################################################

;allow_public_registration = "true"
;admin_enable_required = "true"

; This disable email confirmation when registering.
; DEFAULT: false
;user_no_email_confirm = "false"

;########################################################
; These options control the dynamic downsampling based  #
; on current usage                                      #
; *Note* Transcoding must be enabled and working        #
;########################################################

max_bit_rate = 576
min_bit_rate = 48

;; Audio
transcode_m4a      = allowed
transcode_flac     = required
transcode_mpc      = required
transcode_ogg      = required
transcode_oga      = required
transcode_wav      = required
transcode_wma      = required
transcode_aif      = required
transcode_aiff     = required
transcode_ape      = required
transcode_shn      = required
transcode_mp3      = allowed
;; Video
transcode_avi      = allowed
transcode_mkv      = allowed
transcode_mpg      = allowed
transcode_mpeg     = allowed
transcode_m4v      = allowed
transcode_mp4      = allowed
transcode_mov      = allowed
transcode_wmv      = allowed
transcode_ogv      = allowed
transcode_divx     = allowed
transcode_m2ts     = allowed
transcode_webm     = allowed

; Default audio output format
; DEFAULT: none
encode_target = mp3

; Default video output format
; DEFAULT: none
encode_video_target = webm

; Master transcode command
transcode_cmd = "ffmpeg"

; Transcode input file argument
transcode_input = "-i %FILE%"

; Encoding arguments
; For each output format, you should provide the necessary arguments for your transcode_cmd.
encode_args_mp3 = "-vn -b:a %BITRATE%K -c:a libmp3lame -f mp3 pipe:1"
encode_args_ogg = "-vn -b:a %BITRATE%K -c:a libvorbis -f ogg pipe:1"
encode_args_opus = "-vn -b:a %BITRATE%K -c:a libopus -compression_level 10 -vsync 2 -f ogg pipe:1"
encode_args_m4a = "-vn -b:a %BITRATE%K -c:a libfdk_aac -f adts pipe:1"
encode_args_wav = "-vn -b:a %BITRATE%K -c:a pcm_s16le -f wav pipe:1"
encode_args_flv = "-b:a %BITRATE%K -ar 44100 -ac 2 -v 0 -f flv -c:v libx264 -preset superfast -threads 0 pipe:1"
encode_args_webm = "-q %QUALITY% -f webm -c:v libvpx -maxrate %MAXBITRATE%k -preset superfast -threads 0 pipe:1"
encode_args_ts = "-q %QUALITY% -s %RESOLUTION% -f mpegts -c:v libx264 -c:a libmp3lame -maxrate %MAXBITRATE%k -preset superfast -threads 0 pipe:1"

; Encoding arguments to retrieve an image from a single frame
encode_get_image = "-ss %TIME% -f image2 -vframes 1 pipe:1"

; Encoding argument to encrust subtitle
encode_srt = "-vf \"subtitles='%SRTFILE%'\""

; Encode segment frame argument
encode_ss_frame = "-ss %TIME%"

; Encode segment duration argument
encode_ss_duration = "-t %DURATION%"


;#########################################################
;  Mail Settings                                         #
;#########################################################

;Method used to send mail
;POSSIBLE VALUES: smtp sendmail php
;mail_type = "php"

;Mail domain.
mail_domain = "%%MAIL_DOMAIN%%"

;This will be combined with mail_domain and used as the source address for
;emails generated by Ampache.  For example, setting this to 'me' will set the
;sender to 'me@example.com'.
;DEFAULT: info
mail_user = "%%MAIL_USER%%"

;A name to go with the email address.
mail_name = "%%MAIL_NAME%%"

;How strictly email addresses should be checked.
;easy does a regex match, strict actually performs some SMTP transactions
;to see if we can send to this address.
;POSSIBLE VALUES: strict easy none
; DEFAULT: strict
;mail_check = "strict"


;#########################################################
;  SMTP Settings                                         #
;#########################################################

mail_host = "%%MAIL_HOST%%"
mail_port = %%MAIL_PORT%%
mail_auth = "%%MAIL_AUTH%%"
mail_auth_user = "%%MAIL_AUTHUSER%%"
mail_auth_pass = "%%MAIL_AUTHPASS%%"

;#############################
;   Abbreviation Filter      #
;#############################
; For file name parsing. Any unecessary abbreviations in file names can be removed during parsing
; by adding them to the list below so that they will be removed during the parsing process.
common_abbr = "divx,xvid,dvdrip,hdtv,lol,axxo,repack,xor,pdtv,real,vtv,caph,2hd,proper,fqm,uncut,topaz,tvt,notv,fpn,fov,orenji,0tv,omicron,dsr,ws,sys,crimson,wat,hiqt,internal,brrip,boheme,vost,vostfr,fastsub,addiction,x264,LOL,720p,1080p,YIFY,evolve,fihtv,first,bokutox,bluray,tvboom,info"
